# Generated by Django 3.2.7 on 2021-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20211125_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
