# Generated by Django 3.2.7 on 2021-12-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_agent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
