# Generated by Django 3.2.7 on 2021-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/unknown-person-profile.jpg', null=True, upload_to='profile_picture/'),
        ),
    ]
